version: "3.7"

services:
    seu-aguiar:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - seu-aguiar-network
    # nginx
    nginx:
        container_name: servidor-nginx-seu-aguiar
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8888:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - seu-aguiar-network
     # db mysql ${DB_DATABASE} //Busca do arquivo .env
    mysql:
        container_name: banco-mysql-seu-aguiar
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3377:3306"
        networks:
            - seu-aguiar-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin-seu-aguiar
        links:
            - mysql
        restart: always
        environment:
            - PMA_ARBITRARY=1
        ports:
            - 8890:80
        networks:
            - seu-aguiar-network

networks:
    seu-aguiar-network:
        driver: bridge

#Doc. de utilizacao
# para acessar phpmyadmin no navegador: http://localhost:8888/ -  e a porta
# para acessar nginx(servidor) no navegador: http://localhost:8890/ - e a porta

#PHPMYADMIN info no file
# servidor: mysql
# user: root
# pass: root

